# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FacebookExample
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'FacebookExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FacebookExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FacebookExample-tvOS

  target 'FacebookExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
